FROM node:20.10.0

WORKDIR /app

COPY package.json yarn.lock ./
COPY tsconfig.json .

RUN yarn install

COPY . .

RUN rm src/server.ts

CMD ["node", "-r", "ts-node/register", "--env-file=.env", "-r", "tsconfig-paths/register", "queue/consume-document-messages.ts"]