version: '3.9'

services:
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=${PORT}
        restart: unless-stopped
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - .:/app
