version: '3.9'

services:
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DOCKER_BUILDKIT: 1
        restart: unless-stopped
